### ISSUE TITLE
Incompability with Corail Tombstone

### ISSUE THREAD

**Issue by AleksQuantum** [SiverDX/dragonsurvival_compatibility#2]
Whenever a player in dragon form tries to retrieve their stuff from a tombstone the entire server crashes with clients.

**Comment by SiverDX** [comment]
would need a log for that
also note that i don't do anything with that mod (i think they have their own compatibility code)

**Comment by AleksQuantum** [comment]
```
[31Oct2023 20:32:29.612] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Twilight_Spyro has reached the goal [Easy Opening]
[31Oct2023 20:32:29.615] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'by.dragonsurvivalteam.dragonsurvival.common.capability.subcapabilities.ClawInventory by.dragonsurvivalteam.dragonsurvival.common.capability.DragonStateHandler.getClawInventory()'
	at ovh.corail.tombstone.compatibility.CompatibilityDragonSurvival.lambda$autoEquip$0(CompatibilityDragonSurvival.java:30) ~[tombstone-8.2.2-1.19.2.jar%23207!/:8.2.2]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at ovh.corail.tombstone.compatibility.CompatibilityDragonSurvival.autoEquip(CompatibilityDragonSurvival.java:29) ~[tombstone-8.2.2-1.19.2.jar%23207!/:8.2.2]
	at ovh.corail.tombstone.helper.InventoryHelper.autoequip(InventoryHelper.java:63) ~[tombstone-8.2.2-1.19.2.jar%23207!/:8.2.2]
	at ovh.corail.tombstone.helper.InventoryHelper.autoequip(InventoryHelper.java:50) ~[tombstone-8.2.2-1.19.2.jar%23207!/:8.2.2]
	at ovh.corail.tombstone.tileentity.BlockEntityPlayerGrave.giveInventory(BlockEntityPlayerGrave.java:99) ~[tombstone-8.2.2-1.19.2.jar%23207!/:8.2.2]
	at ovh.corail.tombstone.block.BlockGrave.activatePlayerGrave(BlockGrave.java:76) ~[tombstone-8.2.2-1.19.2.jar%23207!/:8.2.2]
	at ovh.corail.tombstone.block.BlockGrave.m_6227_(BlockGrave.java:54) ~[tombstone-8.2.2-1.19.2.jar%23207!/:8.2.2]
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60664_(BlockBehaviour.java:714) ~[server-1.19.2-20220805.130853-srg.jar%23221!/:?]
	at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:340) ~[server-1.19.2-20220805.130853-srg.jar%23221!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:1060) ~[server-1.19.2-20220805.130853-srg.jar%23221!/:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:34) ~[server-1.19.2-20220805.130853-srg.jar%23221!/:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8) ~[server-1.19.2-20220805.130853-srg.jar%23221!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[server-1.19.2-20220805.130853-srg.jar%23221!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.19.2-20220805.130853-srg.jar%23221!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.19.2-20220805.130853-srg.jar%23221!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.19.2-20220805.130853-srg.jar%23221!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:763) ~[server-1.19.2-20220805.130853-srg.jar%23221!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:157) ~[server-1.19.2-20220805.130853-srg.jar%23221!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.19.2-20220805.130853-srg.jar%23221!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:746) ~[server-1.19.2-20220805.130853-srg.jar%23221!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:740) ~[server-1.19.2-20220805.130853-srg.jar%23221!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[server-1.19.2-20220805.130853-srg.jar%23221!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:725) ~[server-1.19.2-20220805.130853-srg.jar%23221!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:658) ~[server-1.19.2-20220805.130853-srg.jar%23221!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23221!/:?]
	at java.lang.Thread.run(Thread.java:1589) [?:?]
[31Oct2023 20:32:29.707] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID efa6f280-42b6-49c8-acfb-213766220363
[31Oct2023 20:32:29.710] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: This crash report has been saved to: C:\Users\Alex\Desktop\minecraft\minecraft server\.\crash-reports\crash-2023-10-31_20.32.29-server.txt
[31Oct2023 20:32:29.711] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Stopping server
[31Oct2023 20:32:29.711] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving players
[31Oct2023 20:32:29.771] [Server thread/INFO] [net.minecraft.server.network.ServerGamePacketListenerImpl/]: Twilight_Spyro lost connection: Server closed
[31Oct2023 20:32:29.771] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Twilight_Spyro left the game
[31Oct2023 20:32:29.789] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving worlds
[31Oct2023 20:32:31.946] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[31Oct2023 20:32:32.137] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_end
[31Oct2023 20:32:32.142] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/the_bumblezone:the_bumblezone
[31Oct2023 20:32:32.150] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_nether
[31Oct2023 20:32:32.161] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: Saving chunks for level 'ServerLevel[world]'/ae2:spatial_storage
[31Oct2023 20:32:32.219] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (world): All chunks are saved
[31Oct2023 20:32:32.220] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[31Oct2023 20:32:32.221] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (the_bumblezone): All chunks are saved
[31Oct2023 20:32:32.221] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[31Oct2023 20:32:32.221] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage (spatial_storage): All chunks are saved
[31Oct2023 20:32:32.226] [Server thread/INFO] [net.minecraft.server.MinecraftServer/]: ThreadedAnvilChunkStorage: All dimensions are saved
[31Oct2023 20:32:32.387] [Server thread/INFO] [FTB Chunks/]: Shutting down map thread
[31Oct2023 20:32:32.387] [Server thread/INFO] [configured/]: Unloading server configs...
[31Oct2023 20:32:32.388] [Server thread/INFO] [configured/]: Sending config unload event for configured.developer.toml
```

**Comment by SiverDX** [comment]
corail tombstones compat code is out of date, nothing i can do here

**Comment by Corail31** [comment]
@AleksQuantum Your version is not up-to-date (tombstone-8.2.2), you need to be on 8.2.10 for the latest compat with that mod.

**Comment by AleksQuantum** [comment]
Ah, thank you for help. I am unable to update at the time, but I'll see what I can do.
